### ISSUE TITLE
TRO-23-12 - Make Order

### ISSUE THREAD

**Issue by EduardoMartin-Moral** [ProjectCentreLimited/TOMs#163]
Hi,

We (PCL nor CEC) cannot make order TRO-23-12 live.
We have tried using different accounts.

Can you please make this Order live as a matter of urgency?
Please Accept the proposal in TOMS with an Effective Date on 12/02/2024.

This is to be completed before 08/02/2024 10am. If this is not possible, please advise and **DO NOT** make the Order beyond this time.

![image](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/c8b8ff5e-d8ac-44be-b836-14385749efcf)

Thanks
Eduardo

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas @benoitdm-oslandia ,

We need a response from yourselves by 9.30am as if this is not possible to be actioned the Council needs to pull the advert for which they need time.

Thanks
Eduardo

**Comment by Djedouas** [comment]
Hi @EduardoMartin-Moral 

The error message is not trivial, and needs investigation. I'm sorry to inform you that we can't solve this rapidly.

**Comment by EduardoMartin-Moral** [comment]
Thanks @Djedouas,

Can you please find out if the issue is resolvable?

Can you please investigate and confirm if the issue can be resolved by the end of Tuesday, the 13th?

Thanks
Eduardo

**Comment by Djedouas** [comment]
This issue is on hold at the moment. Please get in touch with @SeanC75 if needed.

Regards  
Jacky

**Comment by EduardoMartin-Moral** [comment]
@SeanC75 the Council has just messaged me to let us know that this needs to be urgently resolved by Oslandia by Monday. Ideally they should be able to make the Order mid-morning, so that we can place the advert in time for it to appear in the press on the 16th.

We also need to check whether there should be any issues with making other Orders, i.e. is this issue Order specific, or more widespread?

**Comment by Djedouas** [comment]
The following tiles have a revision date after the effective date of TRO-23-12.

More particularly, tile 1753 is concerned by TRO-23-12. The other tiles may prevent other proposals to be accepted.

It is part of the issue preventing to accept the proposal, because the tiles revision dates must be < proposal effective date.

Do you know why?

Do we
1. change the revision date of those tiles to be < February
2. or the effective date of TRO-23-12 to be > 8th April
3. or remove every restriction geometry for TRO-23-12 on tile 1753?


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"><html><head></head><body>
tile number | x_min | x_max | y_min | y_max | CurrRevisionNr | LastRevisionDate
 -- | -- | -- | -- | -- | -- | --
422 | 313100 | 313500 | 677900 | 678150 | 2 | 2024-04-08 |  
630 | 325500 | 325900 | 677150 | 677400 | 4 | 2024-04-08 |  
683 | 323100 | 323500 | 676900 | 677150 | 4 | 2024-04-08 |  
684 | 323500 | 323900 | 676900 | 677150 | 4 | 2024-04-08 |  
743 | 323500 | 323900 | 676650 | 676900 | 3 | 2024-04-08 |  
808 | 325900 | 326300 | 676400 | 676650 | 6 | 2024-04-08 |  
925 | 325500 | 325900 | 675900 | 676150 | 2 | 2024-04-08 |  
1161 | 325500 | 325900 | 674900 | 675150 | 8 | 2024-04-08 |  
1162 | 325900 | 326300 | 674900 | 675150 | 8 | 2024-04-08 |  
1279 | 325500 | 325900 | 674400 | 674650 | 6 | 2024-04-08 |  
1290 | 329900 | 330300 | 674400 | 674650 | 4 | 2024-04-08 |  
1346 | 328700 | 329100 | 674150 | 674400 | 2 | 2024-04-08 |  
1382 | 319500 | 319900 | 673900 | 674150 | 3 | 2024-04-08 |  
1383 | 319900 | 320300 | 673900 | 674150 | 3 | 2024-04-08 |  
1394 | 324300 | 324700 | 673900 | 674150 | 4 | 2024-04-08 |  
1408 | 329900 | 330300 | 673900 | 674150 | 2 | 2024-04-08 |  
1453 | 324300 | 324700 | 673650 | 673900 | 5 | 2024-04-08 |  
1465 | 329100 | 329500 | 673650 | 673900 | 3 | 2024-04-08 |  
1469 | 330700 | 331100 | 673650 | 673900 | 3 | 2024-04-08 |  
1524 | 329100 | 329500 | 673400 | 673650 | 4 | 2024-04-08 |  
1528 | 330700 | 331100 | 673400 | 673650 | 2 | 2024-04-08 |  
1590 | 331900 | 332300 | 673150 | 673400 | 3 | 2024-04-08 |  
1682 | 321500 | 321900 | 672650 | 672900 | 2 | 2024-04-08 |  
1737 | 319900 | 320300 | 672400 | 672650 | 2 | 2024-04-08 |  
1738 | 320300 | 320700 | 672400 | 672650 | 2 | 2024-04-08 |  
1753 | 326300 | 326700 | 672400 | 672650 | 7 | 2024-04-08 |  
1764 | 330700 | 331100 | 672400 | 672650 | 2 | 2024-04-08 |  
1859 | 321500 | 321900 | 671900 | 672150 | 3 | 2024-04-08 |  
1917 | 321100 | 321500 | 671650 | 671900 | 3 | 2024-04-08 |  
1975 | 320700 | 321100 | 671400 | 671650 | 2 | 2024-04-08 |  
1976 | 321100 | 321500 | 671400 | 671650 | 2 | 2024-04-08 |  
2212 | 321100 | 321500 | 670400 | 670650 | 3 | 2024-04-08 |  
2397 | 324300 | 324700 | 669650 | 669900 | 1 | 2024-04-08 |  
2511 | 322700 | 323100 | 669150 | 669400 | 2 | 2024-04-08 |  
2704 | 329100 | 329500 | 668400 | 668650 | 3 | 2024-04-08 |  

</body></html>

**Comment by EduardoMartin-Moral** [comment]
Hi 

CEC have tried to make TRO-23-12 with an effective date on 09/04/2024 and got the following error
![image](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/5a4dfada-cf9e-4661-b896-28257889e78d)
![image](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/211a1fcb-8abb-4376-9f40-d6f323709885)


Can you please make it yourselves now and let us know when done as the Council needs to sign the Order on the same day?
We do not want the other options being carried out (Option 1 nor 3)

Thanks
Eduardo

**Comment by Djedouas** [comment]
Thanks for your answer. 

Moving on to fix the issue. 

I am confident to finish fixing it on Monday.

**Comment by Djedouas** [comment]
I understand that when the issue is fixed, CEC will make the effective date 9th April. 

Is that correct?

**Comment by EduardoMartin-Moral** [comment]
Yes - unless for whatever reason the system does not let them do that themselves

**Comment by Djedouas** [comment]
Hi,

The issue should be fixed now.

No need to restart TOMS.

CEC should be able to accept the proposal with an effective date on April 9th.  
This proposal is big, so TOMS will freeze for some moment (possibly minutes) after accepting the proposal, but it should process and end correctly.

Please confirm.

Thanks

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas,

Following conversations with CEC it appears that the issue is not fixed.

It looks like the changes proposed under TRO/23/12 have been forced into the live version of TOMS as of the 17th of February, even though the proposal file still exists. Ergo the proposal has not been accepted, the Order has not been signed, the making of the Order has not been advertised and the Order has not been brought into effect, but TOMS has the changes live within the system.

We believe this is not the fix that was requested. Nor is this what we asked to be done –  a fix that would allow the Council to make the Order and to be advised when that fix had been made so that they could arrange the making of the Order. 
Forcing the changes under TRO-23-12 into the live system without going through the proper proposal acceptance channel may have led to potentially hundreds of locations shown incorrectly in TOMS. These restrictions cannot legally be in effect – and because TOMS is the Order, the Order is now wrong.

I attach some screenshots, provided by the Council, showing the restrictions on one map tile as they should be before making 23/12 (existing), the restrictions as to be amended by 23/12 (proposed) and the restrictions as live in TOMS. The proposals are almost completely reflected in the Live version of TOMS.

We still need an Order that is accurate and that reflects what is on-street and most importantly the legal processes that led to the current situation. 

Please advice about:

- What it comprised the fix that was completed?
- Can you fix the issue so CEC can Make the Order themselves, whilst keeping the live restrictions as they are until CEC approves the proposal, sign the Order, advertise the making of the Order and the effective date comes when the changes under this Order will be applied to the live restrictions?

**23_12 Existing**
![23_12 Existing](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/2fdefc61-f1f4-499f-adab-15ffe41bbfb2)

**23_12 Proposed**
![23_12 Proposed](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/62bfe5cd-de82-4c8d-90f5-5936d3cfeeaa)

**Live restrictions**
![TOMS Live 20_02_24](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/01104668-b16d-4248-8367-1444056ea3d2)

Thanks
Eduardo

**Comment by Djedouas** [comment]
Hi @EduardoMartin-Moral 

> It looks like the changes proposed under TRO/23/12 have been forced into the live version of TOMS as of the 17th of February, even though the proposal file still exists.

No such thing has been done. No data has been modified or moved to fix this issue. It was an internal code issue, completely unrelated whatsoever with the database.

What can be seen on the screenshots reveals other problems, probably like bad manipulations from admin users with elevated rights.

Moreover, the 17th of February was a Saturday, not worked here.

As of today, the issue fixed is the one that was asked for. That is to say a bug when accepting the proposal.

Now there should be no bug when being on TRO-23-12 and clicking on OK while accepting the proposal like the following, please try and confirm:

![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/c3c9c883-7fd1-4c78-88d8-bbdba8972fe4)

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas 

Following a discussion with CEC the desired plan off action is as follows:

1. Revert the "0-No proposal shown" (live restrictions) back to 16/02/2024 so that ALL restrictions are as they were on that date. This will have the effect of nullifying two Orders made after that date (proposals TRO-23-38 and TRO-22-18) and will remove the proposals for proposal TRO-23-12 that have now appeared in the live restrictions.
2. Reinstate the proposal for TRO-23-38 and then bring it into the live version of TOMS with a making date of 12/02/24 and an Effective Date of 18/02/24
3. Reinstate the proposal for TRO-22-18 and then bring it into the live version of TOMS with a making date of 12/02/24 and an Effective Date of 08/04/24
4. Notify us when these changes have been made so that CEC can then check if they can accept the proposal for TRO-23-12 and select Effective Date of 09/04/24, as you show in your screenshot.

Many thanks
Eduardo

**Comment by Djedouas** [comment]
Hi @EduardoMartin-Moral ,

This is a tricky data modification.

We will do steps 1., 2., and 3. first in TOMS STAGING version, then someone from CEC will have to confirm that everything is ok, even accepting TRO-23-12.

Then we will replicate staging database on live version of TOMS.

We need to know which account needs access to staging version of TOMS (Gavin Reid, Darren Young, and Holly Robertson already have access).

Thanks

**Comment by Djedouas** [comment]
We can't do steps 2. and 3. 

TRO/23/38 and TRO/22/18 have not been nullified by reverting the database to February 16th.  
TRO/23/38 and TRO/22/18 have been both accepted on February 12th, respectively at 10h23 and 10h26.

Now, the "0-No proposal shown" on the STAGING version of TOMS is on the state of the LIVE version on February 16th.

You can tell us which account we can give access to this STAGING version, so the person can perform the desired checks.

**Comment by EduardoMartin-Moral** [comment]
Hi @Djedouas 

We have checked the Staging version and we believe that the Live Restrictions do not match the live restriction on the 16th February. 

The Live Restriction in the Staging version currently shows the changes under TRO-23-12 as if these would have already been applied. Please refer to the two locations shown below.
![image](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/a16ee81d-e546-4e84-bbce-ab0262b2af1d)
![image](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/a6b28319-3a7c-4512-9fcc-c9ba3ae7f70b)

Furthermore, we do not understand the timings associated with the 'Last Update' field for the bays that seem to be edited as part of these TRO-23-12 proposal. These changes should have not been applied as this proposal is still to be accepted following the fix of the bug. However, the time stamp for the Last Update field is 10:26 on the 12th of February. That timestamp matches the making of TRO-22-18 which does not include any changes to this particular bay.

![image](https://github.com/ProjectCentreLimited/TOMs/assets/117166421/baa1bf49-7d3d-4949-bef1-307c945e99d5)


Can you please revert the Live Restrictions in the Staging Version so that the current restrictions are shown as per those on the 16th February?

Thanks

**Comment by bparpoil** [comment]
Hello, the initial bug that was the subject of this ticket (python error) has been fixed. Is it possible to please mark this ticket solved, close it and create new tickets for the new bugs detected? in order to better understand the situation. Thanks in advance!

**Comment by EduardoMartin-Moral** [comment]
Hi @bparpoil,

Unfortunately, the Council has not been able to confirm if the python error that prevented TRO-23-12 from being made has been solved.
They have not attempted to make the order as a result of the identification of the issues described above at the locations where TRO-23-12 was going to introduce changes to the parking restrictions.

Happy for you to categorise this #163 as 'Awaiting Client Feedback'

Thanks
